Configuration File
==================

Project: ${project_name}
Environment: ${environment}
Generated: ${timestamp}

Application Settings:
- Debug Mode: ${environment == "development" ? "enabled" : "disabled"}
- Log Level: ${environment == "production" ? "warning" : "debug"}
- Cache Enabled: ${environment == "production" ? "true" : "false"}

Notes:
This file is automatically generated by Terraform.
Manual changes will be overwritten.
